name: Verify docs generation

# Runs on pushes to master and all pull requests
on:    # yamllint disable-line rule:truthy
    push:
        branches: [main, develop]
    pull_request:

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
            - name: Full dependencies
              run: |
                  # up to k2 compatible torch version
                  pip install torch==2.1.2 torchaudio==2.1.2
                  pip install -r requirements.txt
                  pip install --editable .
                  pip install -r docs/docs-requirements.txt
                  pip install k2==1.24.4.dev20231220+cpu.torch2.1.2 -f https://k2-fsa.github.io/k2/cpu.html
            - name: Generate docs
              run: |
                  cd docs
                  make html
