# ################################
# Model: Whisper (Encoder-Decoder) + NLL
# Augmentation: TimeDomainSpecAugment
# Authors: Pooneh Mousavi 2022
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]
experiment_folder: !PLACEHOLDER
output_folder: !ref <experiment_folder>/results/whisper_enc_dec_small_test/<seed>
output_wer_folder: !ref <output_folder>/
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: /workspace/SpokenMedicalQA_data/data-30+/
train_csv: !ref <data_folder>/MedMCQA_train.csv
valid_csv: !ref <data_folder>/MedMCQA_validation.csv
test_csv:
   - !ref <data_folder>/MedMCQA_test.csv
   #- !ref <data_folder>/MedQA_test_transcription.csv
   #- !ref <data_folder>/MMLU_anatomy_test_transcription.csv
   #- !ref <data_folder>/MMLU_clinical_knowledge_test_transcription.csv
   #- !ref <data_folder>/MMLU_college_biology_test_transcription.csv
   #- !ref <data_folder>/MMLU_college_medicine_test_transcription.csv
   #- !ref <data_folder>/MMLU_medical_genetics_test_transcription.csv
   #- !ref <data_folder>/MMLU_professional_medicine_test_transcription.csv

# remove utt length longer than 30 seconds
locale: en
avoid_if_longer_than: 30.0
ckpt_interval_minutes: 5 # save checkpoint every N min

# URL for the biggest Fairseq english whisper model.
whisper_hub: openai/whisper-small
normalized_transcripts: True

freeze_whisper: False
freeze_encoder: False

####################### Training Parameters ####################################
number_of_epochs: 5
lr_whisper: 6.25e-6
sorting: ascending
precision: fp32 # bf16, fp16 or fp32
sample_rate: 16000

# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
batch_size: 8
test_batch_size: 8

# These values are only used for the searchers.
# They needs to be hardcoded and should not be changed with Whisper.
# They are used as part of the searching process.
# The bos token of the searcher will be timestamp_index
# and will be concatenated with the bos, language and task tokens.
timestamp_index: 50363
eos_index: 50257
bos_index: 50258

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 1.0

############################## Augmentations ###################################
# Speed perturbation
speed_perturb: !new:speechbrain.augment.time_domain.SpeedPerturb
    orig_freq: !ref <sample_rate>
    speeds: [95, 100, 105]

# Frequency drop: randomly drops a number of frequency bands to zero.
drop_freq: !new:speechbrain.augment.time_domain.DropFreq
    drop_freq_low: 0
    drop_freq_high: 1
    drop_freq_count_low: 1
    drop_freq_count_high: 3
    drop_freq_width: 0.05

# Time drop: randomly drops a number of temporal chunks.
drop_chunk: !new:speechbrain.augment.time_domain.DropChunk
    drop_length_low: 1000
    drop_length_high: 2000
    drop_count_low: 1
    drop_count_high: 5

# Augmenter: Combines previously defined augmentations to perform data augmentation
wav_augment: !new:speechbrain.augment.augmenter.Augmenter
    min_augmentations: 3
    max_augmentations: 3
    augment_prob: 1.0
    augmentations: [
        !ref <speed_perturb>,
        !ref <drop_freq>,
        !ref <drop_chunk>]

####################### Model Parameters #######################################

train_loader_kwargs:
    batch_size: !ref <batch_size>

valid_loader_kwargs:
    batch_size: !ref <test_batch_size>

test_loader_kwargs:
    batch_size: !ref <test_batch_size>

#
# Functions and classes
#
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>


############################## Models ##########################################


whisper: !new:speechbrain.lobes.models.huggingface_transformers.whisper.Whisper
    source: !ref <whisper_hub>
    freeze: !ref <freeze_whisper>
    freeze_encoder: !ref <freeze_encoder>
    save_path: !ref <save_folder>/whisper_checkpoint
    encoder_only: False

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

nll_loss: !name:speechbrain.nnet.losses.nll_loss

modules:
    whisper: !ref <whisper>

whisper_opt_class: !name:torch.optim.AdamW
    lr: !ref <lr_whisper>
    weight_decay: 0.01
    betas: (0.9, 0.98)
    eps: 1.e-8

searcher: !new:speechbrain.decoders.seq2seq.S2SWhisperGreedySearch
    model: !ref <whisper>
    bos_index: !ref <timestamp_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>

# searcher: !new:speechbrain.decoders.seq2seq.S2SWhisperBeamSearch
#     module: [!ref <whisper>]
#     bos_index: !ref <timestamp_index>
#     eos_index: !ref <eos_index>
#     min_decode_ratio: !ref <min_decode_ratio>
#     max_decode_ratio: !ref <max_decode_ratio>
#     beam_size: 1

# lr_annealing_whisper: !new:speechbrain.nnet.schedulers.NewBobScheduler
#     initial_value: !ref <lr_whisper>
#     improvement_threshold: 0.0025
#     annealing_factor: 0.9
#     patient: 0

lr_annealing_whisper: !new:speechbrain.nnet.schedulers.NoamScheduler
   lr_initial: !ref <lr_whisper>
   n_warmup_steps: 100


checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        whisper: !ref <whisper>
        scheduler_whisper: !ref <lr_annealing_whisper>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True
